version: '3.9'

services:
  bot:
    build: .
    image: white-whale-bot
    container_name: white-whale-bot
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true    
